import 'dotenv/config'
import mongoose from 'mongoose'
import { connectDB } from '../config/db.js'
import Product from '../models/Product.js'

const products = [
  {
    title: 'Brilliant Art',
    price: 350,
    image: 'https://picsum.photos/id/1026/600/750',
    description: 'A vibrant abstract composition erupting with raw energy — bold strokes of crimson, gold, and white create a living tapestry of color and movement.',
    creator: 'A. Marin',
    year: 2021,
    medium: 'Oil on canvas',
    size: '28 cm × 35 cm × 2 cm',
    material: 'Canvas',
    category: 'Abstract',
    theme: ['Modern', 'Abstract'],
    frameType: 'Canvas',
    tags: ['abstract', 'bold', 'colorful'],
    inStock: true,
    soldCount: 24,
  },
  {
    title: 'Dragon Art',
    price: 1200,
    image: 'https://picsum.photos/id/244/600/750',
    description: 'A masterful fantasy composition featuring a mythical dragon emerging from swirling cosmic energies. Hand-painted with premium metallic pigments on gallery-grade canvas.',
    creator: 'K. Zhou',
    year: 2023,
    medium: 'Acrylic on canvas',
    size: '60 cm × 80 cm × 3 cm',
    material: 'Canvas',
    category: 'Fantasy',
    theme: ['Fantasy', 'Mythical'],
    frameType: 'Canvas',
    tags: ['fantasy', 'dragon', 'mythical'],
    inStock: true,
    soldCount: 8,
  },
  {
    title: 'Creative Art',
    price: 220,
    image: 'https://picsum.photos/id/1015/600/750',
    description: 'Serene water lilies float in still emerald water, inspired by the Impressionist masters. A meditative study of light, reflection, and the beauty of stillness.',
    creator: 'L. Okoye',
    year: 2020,
    medium: 'Watercolor on paper',
    size: '22 cm × 30 cm × 1 cm',
    material: 'Synthetic',
    category: 'Landscape',
    theme: ['Modern', 'Abstract', 'Landscape'],
    frameType: 'Paper',
    tags: ['floral', 'water', 'impressionist'],
    inStock: true,
    soldCount: 63,
  },
  {
    title: 'Canvas Art',
    price: 550,
    image: 'https://picsum.photos/id/237/600/750',
    description: 'A striking equine portrait capturing raw power and grace — rich ochres and burnt sienna set against a dramatic dark background.',
    creator: 'M. Rivera',
    year: 2022,
    medium: 'Oil on linen',
    size: '40 cm × 50 cm × 2 cm',
    material: 'Linen',
    category: 'Portrait',
    theme: ['Classic', 'Portrait'],
    frameType: 'Canvas',
    tags: ['horse', 'portrait', 'oil'],
    inStock: true,
    soldCount: 15,
  },
  {
    title: 'Art Magic',
    price: 1250,
    image: 'https://picsum.photos/id/305/600/750',
    description: 'Swirling vortices of amber and rust create an otherworldly landscape. A premium high-definition art piece printed on archival material.',
    creator: 'R. Alvarez',
    year: 2022,
    medium: 'Oil on linen',
    size: '28 cm × 35 cm × 2 cm',
    material: 'Synthetic',
    category: 'Abstract',
    theme: ['Modern', 'Abstract', 'Landscape'],
    frameType: 'Canvas',
    tags: ['abstract', 'orange', 'swirl'],
    inStock: true,
    soldCount: 63,
  },
  {
    title: 'Midnight Bloom',
    price: 480,
    image: 'https://picsum.photos/id/1062/600/750',
    description: 'A nocturnal floral study with jewel-deep contrasts — crimson blooms emerge from velvety darkness in a celebration of botanical splendour and shadow.',
    creator: 'S. Patel',
    year: 2021,
    medium: 'Oil on board',
    size: '30 cm × 40 cm × 2 cm',
    material: 'Board',
    category: 'Floral',
    theme: ['Classic', 'Floral'],
    frameType: 'Canvas',
    tags: ['floral', 'dark', 'botanical'],
    inStock: true,
    soldCount: 31,
  },
  {
    title: 'Ocean Study',
    price: 380,
    image: 'https://picsum.photos/id/1018/600/750',
    description: 'A serene coastal study capturing the ever-changing light of the sea at dusk, with layered blues and shimmering horizon highlights.',
    creator: 'A. Marin',
    year: 2019,
    medium: 'Oil on canvas',
    size: '35 cm × 28 cm × 2 cm',
    material: 'Canvas',
    category: 'Landscape',
    theme: ['Coastal', 'Seascape'],
    frameType: 'Canvas',
    tags: ['seascape', 'ocean', 'blue'],
    inStock: false,
    soldCount: 42,
  },
  {
    title: 'Forest Mist',
    price: 290,
    image: 'https://picsum.photos/id/1043/600/750',
    description: 'Soft atmospheric light filters through ancient woodland in this meditative landscape — peaceful, contemplative, and deeply evocative of early morning silence.',
    creator: 'L. Okoye',
    year: 2020,
    medium: 'Watercolor on paper',
    size: '24 cm × 32 cm × 1 cm',
    material: 'Paper',
    category: 'Landscape',
    theme: ['Nature', 'Atmospheric'],
    frameType: 'Paper',
    tags: ['forest', 'mist', 'nature'],
    inStock: true,
    soldCount: 19,
  },
]

async function seed() {
  await connectDB()
  await Product.deleteMany({})
  const inserted = await Product.insertMany(products)
  console.log(`Seeded ${inserted.length} products`)
  await mongoose.disconnect()
}

seed().catch(err => {
  console.error(err)
  process.exit(1)
})
